name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          docker build -t bloodline-frontend:latest ./frontend
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker tag bloodline-frontend:latest <DOCKER_HUB_USERNAME>/bloodline-frontend:latest
          docker push <DOCKER_HUB_USERNAME>/bloodline-frontend:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <FRONTEND_AZURE_WEB_APP_NAME>
          images: <DOCKER_HUB_USERNAME>/bloodline-frontend:latest
