name: CI/CD Pipeline

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t bloodline-frontend:latest ./frontend
          docker tag bloodline-frontend:latest onaliy/bloodline-frontend:latest
          docker push onaliy/bloodline-frontend:latest

      # - name: Deploy Frontend to Azure App Service
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: bloodlinehealth
      #     images: onaliy/bloodline-frontend:latest
