name: CI/CD Pipeline

on:
  push:
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env.production
        run: |
          echo "VITE_CLIENT_ID=${{ secrets.VITE_CLIENT_ID }}" >> frontend/.env.production
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> frontend/.env.production
          echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" >> frontend/.env.production
          echo "VITE_IS_PRODUCTION=true" >> frontend/.env.production
          echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}" >> frontend/.env.production

      - name: Build and Push Docker Image
        run: |
          docker build -t bloodline-frontend:latest ./frontend
          docker tag bloodline-frontend:latest onaliy/bloodline-frontend:latest
          docker push onaliy/bloodline-frontend:latest

      - name: Deploy Frontend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: bloodline
          images: onaliy/bloodline-frontend:latest
