name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t bloodline-frontend:latest ./frontend
        docker tag bloodline-frontend:latest onaliy/bloodline-frontend:latest
        docker push onaliy/bloodline-frontend:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: bloodlinehealth
        images: onaliy/bloodline-frontend:latest
